twelvelabs-io/twelvelabs-js

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

chore: templates

---

examples/classify.ts
examples/generate.ts
examples/search.ts
examples/task.ts
examples/video.ts
src/index.ts
src/models/classify/index.ts
src/models/index.ts
src/models/interfaces.ts
src/models/search/index.ts
src/resources/classify/index.ts
src/resources/classify/interfaces.ts
src/resources/index.ts

Add classify apis

---

examples/embed.ts
src/index.ts
src/models/embed/index.ts
src/models/index.ts
src/models/task/index.ts
src/resources/embed/index.ts
src/resources/embed/interfaces.ts
src/resources/index.ts

Added Embed APIs. Please refer to these docs:
- [text embeddings](https://docs.twelvelabs.io/reference/text-embeddings)
- [video embeddings](https://docs.twelvelabs.io/reference/video-embeddings)

Add Embed APIs

---

src/resources/embed/index.ts
src/resources/task/index.ts
src/util.ts

validate file exists with both `string` and `ReadableStream` types and attach to form data.

feat: form file input validation

---

README.md

Fixed two code blocks that were using `py` instead of `js`

Code blocks should use `js`

---

README.md

Update the README file for the Image-to-video search feature

Update the README file for the Image-to-video search feature

---

README.md
examples/engine.ts

Updated model names (pegasus1 -> pegasus1.1)

feat: update model names

---

src/core.ts
src/models/embed/index.ts
src/models/task/index.ts

Added `no-cache` header and try-catch logic into wait-related methods

feat: enhance wait methods

---

README.md

Increase video duration to 30 minutes.

Pegasus: Increase video duration to 30 minutes.

---

README.md

Update the README file for Pegasus 1.1

Pegasus1.1

---

src/resources/search/index.ts
src/resources/search/interfaces.ts

Added `adjust_confidence_level` into search params

fix: add `adjust_confidence_level` into search params

---

src/models/video/index.ts

Added `source` in Video object

feat: add `source` in Video object

---

README.md

Update the link to the Dashboard page

Update the link to the Dashboard page

---

README.md

Retrieve your API key: Improve clarity

---

src/models/index/index.ts
src/resources/video/index.ts

fixed inconsistent models and API endpoint for retrieving thumbnail.

fix: inconsistent models and api endpoint

---

README.md

Update minimum resolution
- [X ] Documentation update
- [ X] I have read the [CONTRIBUTING.md](https://github.com/twelvelabs-io/twelvelabs-python/blob/main/CONTRIBUTE.md) document.
- [ X] I have ensured my PR title is descriptive and in imperative mood.
- [ X] I have added necessary documentation (if appropriate).

Update minimum resolution

---

src/models/video/index.ts

added `Embedding` response to video model

fix: add embedding response to video

---

src/models/video/index.ts

fixed `embedding` type in `video` model

fix video.embedding field type

---

src/resources/search/index.ts

search-v2 no longer exists in apiv1.3, should be changed to use /search

fix: incorrect search endpoint

---

README.md
examples/index.ts
src/resources/index/interfaces.ts

supports pegasus-1.2 in create-index input, and updated example code and README

feat: support pegasus1.2

---

examples/generate.ts
src/models/generate/index.ts
src/models/video/index.ts
src/resources/generate/index.ts
src/resources/generate/interfaces.ts

feat: re-support gist api

---

examples/task.ts
src/core.ts
src/index.ts
src/models/index/index.ts
src/models/task/index.ts
src/resources/search/index.ts
src/resources/task/index.ts
src/util.ts
tsconfig.json

This PR is derived from [this issue](https://github.com/twelvelabs-io/twelvelabs-js/issues/81). Since Bun.js handles FormData differently compared to Node.js, added logic to detect the execution environment and process FormData accordingly.
(and removed deprecated API - task status)
- node env
- bun env

feat: support Bun.js

---

README.md

Adding Bun as a supported JS runtime environment.

Bun support

---

examples/task.ts
src/models/video/index.ts
src/resources/task/index.ts
src/resources/task/interfaces.ts
src/resources/video/index.ts
src/resources/video/interfaces.ts

Removed support for `language` and `indexed_at`

Remove support for language and indexed_at

---

src/models/generate/index.ts

added two missing fields - `usage` and `highlight_summary`
API Docs: https://docs.twelvelabs.io/reference/summarize

Missing fields on generate

---

src/models/task/index.ts

`videoId` type in the response model was wrong - it should be `string`

fix: type of videoId

---

src/resources/task/index.ts

Add `provide_transcription` to `TRUE` when setting `transcription_url` - otherwise, the API errors out automatically

fix: add provide_transcription on transcription_url

---

README.md

Contributors guide: https://github.com/twelvelabs-io/twelvelabs-python/blob/main/CONTRIBUTING.md -->
Analyze API

Analyze API

---

README.md

Characters -> tokens

---

.fernignore

add temporal readme to fernignore

chore: fernignore includes beta readme
